### ISSUE TITLE
No welcome email with Custom Email and User Moderation enabled

### ISSUE THREAD

**Issue by jfarthing84** [jfarthing84/theme-my-login#44]
In 6.4.2, I changed the action that TML hooks onto to change the welcome email to  register_post. Unfortunately, that action will not be called when user moderation is active on either activation or admin approval, so the custom emails will not be sent.

**Comment by jfarthing84** [comment]
Fixed in 9317086fd93ce2322508546663212623ac0c4665.

**Comment by ghost** [comment]
Thank you Jeff!
6.4.3 resolves the problems I saw.  Perfect!
FWIW, I use email confirmation. The activation message is sent and works as expected.
After activation, a custom "Welcome" message is sent (registration completion) as expected.

Exactly as I wanted. THANKS for the very quick attention and resolution!

**Comment by stilefano** [comment]
I still have the problem. New welcome email works only without user moderation.
Plugin and Wordpress are both updated.
Could you please help me?
Thanks!

**Comment by jfarthing84** [comment]
What kind of moderation are you using?

**Comment by stilefano** [comment]
By Admin Approval. User are, by default assigned, as subscriber (don't know
if this could change something).
