### ISSUE TITLE
Lost Password Page Showing Login Form Instead

### ISSUE THREAD

**Issue by ignisium** [jfarthing84/theme-my-login#69]
TML Build 6.4.5 running on Wordpress 4.5.2 is showing the login form on the lost password page. Clicking the forgot password link continues to reproduce the issue.

I should note that until the latest update, the lost password form was working fine.

**Comment by cliffdemandt** [comment]
Hi,

I am also experiencing this problem with the 6.4.4 version. 
So I switched back to the new version (6.4.5).

I am using a multilanguage site and the reset password form only shows correct in english. In NL EN and DK it shows the login form.

Also I did not succeed in translating the "lost password" link. The pages exist in all language with the [theme-my-login] shortcode. I also added the latest translation files and translated the plugin using WPML string translation.

Can you please help?

english: [https://www.mysupplements.eu/en/lostpassword/]() (works correct)
dutch: [https://www.mysupplements.eu/wachtwoord-vergeten/]()(shows login form instead, and doesn't translate "lost password"-link)

Kind regards,

Cliff
info@cliffdemandt.nl

**Comment by jfarthing84** [comment]
Can you verify:
- The lost password pages exists
- It isn't in the trash
- It has a custom meta field `_tml_action` with a value of **lostpassword**

**Comment by Vad1mo** [comment]
I actually have a somehow similar similar issue. I am using the enfold theme with the avia layout builder.

I hadn't any problems in styling the login page with the shortcode, But when I tried the lostpassword page it displays the the login form instead. 
After deleting the whole page content except for the shortcode `[theme-my-login]` it was possible to see the lostpassword form. 

Also the  the `_tml_action` meta field isn't set on any of the TML pages and it is also not possible to set the _tml_action  as the _ (underscore) seems not to be allowed Error message: `Please provide a custom field value.`

TML Version: 6.4.5
WP: 4.6.1

**Comment by Vad1mo** [comment]
fixed the issue by providing the proper action form

```
[theme-my-login default_action="register"]
```

see http://docs.thememylogin.com/shortcode/

**Comment by jfarthing84** [comment]
Closing this issue as the OP hasn't responded.

**Comment by zagarskas** [comment]
I had the same problem, found this thread and attempted to fix but have not resolved the problem.

**Problem:** 
when users click on "lost password" from the login page they are directed to:  ?action=lostpassword
and it works, however, when users go to the PAGE URL /lostpassword the login page shows again instead of the TML lost password template.

Few observations/questions
#1- _tml_action with an underscore can not be saved into custom meta fields
see: https://core.trac.wordpress.org/ticket/31225
**Question: is that a typo? should the value be tml_action**

#2- I have read through the documentation and there are some questions:
http://docs.thememylogin.com/shortcode/
**What are the possible values for the following:**
default_action = what are all possible values

_After digging through the core plugin I assume them to be:_
register || lostpassword || retrievepassword || resetpass || rp || login

However I can not find clear documentation as to what exactly they will do, furthermore, on experimentation the results are not clear. 

For example - the following do _not_ have the expected result:
[theme-my-login default_action="rp"]
[theme-my-login default_action="resetpass"]
[theme-my-login default_action="lostpassword"]

My goal here is simple: 
I want to create the pages needed for TML to work by having a list of shortcodes that can be copied and pasted in.

**What short-codes go into the following pages?**
_Assume that each of the following may or may not be child pages and the shortcode is typed into the main body_
WORKS: Login - user/login - [theme-my-login default_action="login"]
WORKS: Register- user/signup - [theme-my-login default_action="register"]
NOT Work: Lost Password- user/lost - [theme-my-login default_action="lostpassword"]
NOT Work: Lost Password- user/reset-pass - [theme-my-login default_action="resetpass"]

Do these pages need some other custom meta var added to them?
Idea: maybe an ADMIN settings panel that has a drop menu with a list of pages would make this process easier, or, an "auto generate required pages" action that could appear here: admin.php?page=theme_my_login

**Comment by zagarskas** [comment]
I has the same problem. 
This thread helped so I am posting here for posterity

Simply adding the following code to my "lost password" page in WordPress does not work.

URL: site.com/lost-password
Contents of main body
```
[theme-my-login instance="2" default_action="lostpassword" login_template="lostpassword-form.php"]
[theme-my-login default_action="lostpassword" login_template="lostpassword-form.php"]
[theme-my-login default_action="lostpassword"]
[theme-my-login]
```

None of the above trigger the proper "forgot password" URL within $template->the_action_links

**Note: in WordPress values that start with underscore can not be saved into the page using custom fields**
- https://core.trac.wordpress.org/ticket/17850
- https://core.trac.wordpress.org/ticket/31225

> "By default, any meta field with an underscore prefix is considered "protected" unless otherwise configured as unprotected."

It should also be noted that the documentation make an _ambiguous_ reference to "Page Id" on this page: http://docs.thememylogin.com/general/
but no such field exists within settings, tools, nor options...

SOLUTION: 
**Therefore to get my pages working** I had to inject `_tml_action` into the `post_meta` database table manually and then I was able to get the "login url" to work properly via the_action_links(). this thread helped me accomplish that because `_tml_action` is not covered in the documentation in a useful way. 
 `meta_key=tml_action meta_value=lostpassword` with id set to the page I was working on

Be aware that this happened to me because we made a NEW version of the lostpassword page and had no way to carry over the custom post meta values that started with an underscore.

**Idea:**
a TML settings panel where we can pull pages from a select list and assign them. it could be as simple as calling add_post_meta() on save of that options panel.

I was thinking about building an addon that does this. (ie: lets users intuitively assign TML pages using a drop menu settings panel) do you have anything in the works already, or, is there a TML extension that addresses this issue?

cheers.
Keywords:
theme-my-login lost password link not working
theme-my-login lost password URL does not trigger
theme-my-login missing lost password action page
theme-my-login _tml_action as post_meta
